<?php

namespace Tests\Feature\MyTest\super;

use App\Models\Hour;
use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class superAdministratorTest extends TestCase
{

    use RefreshDatabase;

//    public function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->artisan('db:seed');
//    }


    /** @test */
    public function super_admin_can_add_new_staff_to_database()
    {
        $this->withoutExceptionHandling();

        $role = Role::factory()->create(['name' => 'superadministrator']);
        $user = User::factory()->create();
        $user->attachRole($role);

        $response = $this->actingAs($user)->get('/addNewPerson');
        $this->assertCount(1, User::all());
        $response->assertViewIs('super.registration');
    }

    /** @test */
    public function super_admin_send_post_on_add_new_person()
    {
        $this->withoutExceptionHandling();

        $role = Role::factory()->create(['name' => 'superadministrator']);
        $role2= Role::factory()->create(['name' => 'administrator']);
        $user = User::factory()->create();
        $user->attachRole($role);

        $this->assertCount(2, Role::all());
        $response = $this->actingAs($user)->post('/addNewPerson',['name' => 'farshad', 'email' => 'farshad@app.com', 'password' => 'password', 'role_id' => 'administrator']);
        $this->assertCount(2, User::all());
    }

    /** @test */
    public function super_can_add_hour()
    {
        $this->withoutExceptionHandling();
        $role = Role::factory()->create(['name' => 'superadministrator']);
        $permission = Permission::factory()->create(['name' => 'hour-create']);
        $user = User::factory()->create();
        $user->attachRole($role);
        $user->attachPermission($permission);

        $this->actingAs($user)->post('/createNewHour' , $this->data($user));

        $hour = Hour::first();

        $this->assertCount(1, Hour::all());
        $this->assertEquals(Hour::first()->user_id, $user->id);
    }

    public function data(User $user): array
    {
        return [
            'user_id' => $user->id,
            'Date' => '1983/02/05',
            'Hour' => '800',
        ];
    }
}
