<?php

namespace Tests\Unit;

use App\Models\Hour;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class HourTest extends TestCase
{

    use RefreshDatabase;

        public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');
    }

    /** @test */
    public function make_new_hour()
    {

        Hour::firstOrCreate([
            'user_id' => 1,
            'date' => '1983/02/05',
            'hour' => 800
        ]);

        $this->assertCount(1, Hour::all());
    }
}
